### ISSUE TITLE
[Feature] Global "utf8" action parameter

### ISSUE THREAD

**Issue by ALIENQuake** [BGforgeNet/msg2po#11]
Can you add a global "utf8" action parameter? Probably the easiest way to do it is to alter the [get_enc function 
](https://github.com/search?q=repo%3ABGforgeNet%2Fmsg2po+%22def+get_enc%22&type=code) so it will ignore all encodings (also DOS_ENCODINGS since Russian players want setup.tra in English) and just save everything as utf8.

**Comment by burner1024** [comment]
Did you try it with all paths? Text goes 3 ways, it's not just unpoify.

Did you try the [encoding parameter](https://github.com/BGforgeNet/msg2po/blob/02da044164ea500d913167b1eba1d697c3eafa8a/msg2po/config.py#L12)?

>  Russian players want setup.tra in English

Don't know where you got that idea, seems like unfounded generalization. Anyway, if setup.tra is in ascii, then open encoding doesn't matter in the first place.

**Comment by ALIENQuake** [comment]
1. Encoding parameter didin't worked:

**Comment by ALIENQuake** [comment]
1. Using my hack:
Hive>po>tra works,
editing .po file directly also works: https://github.com/InfinityMods/Ascension/commit/264da235beaff70e83c35c3957d51dcb3d86d3db
https://github.com/InfinityMods/Ascension/actions/runs/7717817604
editing tra files works:
https://github.com/InfinityMods/Ascension/commit/1f8727fece593381c6eff0cec8a50150aac1f329
https://github.com/InfinityMods/Ascension/actions/runs/7717848964

2. Adding `encoding: utf8` to .bgforge.yml didn't work: https://github.com/InfinityMods/WeiDU-Weblate-GitHub/actions/runs/7717692181/job/21037326982#step:3:238

3. The idea comes from the report from Russian translators: some of them use Win XP, some Win 7 while others Win 10. They don't want to have a mess with console encoding so they asked for English setup.tra.

**Comment by ALIENQuake** [comment]
I've noticed that the name of the utf encoding is: `utf-8` not `utf8` (-). I've [changed](https://github.com/InfinityMods/WeiDU-Weblate-GitHub/commit/0165909dfc8c968abc2529035168641f272018cb) it but it also [didn't work](https://github.com/InfinityMods/WeiDU-Weblate-GitHub/actions/runs/7717955701/job/21038204237).

**Comment by burner1024** [comment]
Added in dev branch.

**Comment by ALIENQuake** [comment]
@burner1024 It is nice to see those two choices separated. I've sent a minor PR with the all_utf8_yes_really_all > all_utf8_also_console change.

**Comment by burner1024** [comment]
Released.

**Comment by burner1024** [comment]
I enabled utf8  by default for console files.
