### ISSUE TITLE
Poify not working

### ISSUE THREAD

**Issue by egornovivan** [BGforgeNet/msg2po#2]
Python 3.7.3 Google Cloud Shell
![изображение](https://user-images.githubusercontent.com/60801856/89103707-3cfc3580-d42d-11ea-9b5e-5fa2024c02dd.png)

python-3.8.5-amd64 windows10
![изображение](https://user-images.githubusercontent.com/60801856/89103726-6c12a700-d42d-11ea-8116-c7446fa89cf9.png)
or am I starting incorrectly?
[english.zip](https://github.com/BGforgeNet/msg2po/files/5010703/english.zip)

**Comment by burner1024** [comment]
The invocation is correct.
The files do work for me on linux (Python 3.6.9):
```
$ poify
.bgforge.yml not found, assuming defaults
Found directory ./english
credits.txt is TXT, but not indexed. Skipping!
quotes.txt is TXT, but not indexed. Skipping!
processing cuts/boil1.sve with encoding cp1252
processing cuts/boil2.sve with encoding cp1252
...
```

Try printing some vars around [this line](https://github.com/BGforgeNet/msg2po/blob/bb67ca0ab602166a40027535d564e0d7befe2b4e/poify#L61).

**Comment by egornovivan** [comment]
so?
![изображение](https://user-images.githubusercontent.com/60801856/89110437-07267380-d464-11ea-94c7-a4b7e18b48f7.png)

**Comment by burner1024** [comment]
first set of prints is too early, drop it

**Comment by egornovivan** [comment]
![изображение](https://user-images.githubusercontent.com/60801856/89110522-c0854900-d464-11ea-84c8-c96d3b00d6ef.png)

![изображение](https://user-images.githubusercontent.com/60801856/89110510-ae0b0f80-d464-11ea-9c54-281b6ff1a680.png)

**Comment by egornovivan** [comment]
python-3.6.8-amd64 windows10, doesn't work either

**Comment by burner1024** [comment]
Try with [debug](https://github.com/BGforgeNet/msg2po/tree/debug) branch.

**Comment by egornovivan** [comment]
debug
![изображение](https://user-images.githubusercontent.com/60801856/89110961-d6e1d380-d469-11ea-87e1-1c88ebbcb1bd.png)

**Comment by burner1024** [comment]
Well, you could try adding some debug to pathlib to see what gets into fspath.

**Comment by egornovivan** [comment]
![изображение](https://user-images.githubusercontent.com/60801856/89111739-d568d900-d472-11ea-9309-f772bd907c77.png)
![изображение](https://user-images.githubusercontent.com/60801856/89111752-fb8e7900-d472-11ea-918f-a58c83b485b4.png)



![изображение](https://user-images.githubusercontent.com/60801856/89111710-7b681380-d472-11ea-97d9-a2b0538f0195.png)
...
![изображение](https://user-images.githubusercontent.com/60801856/89112101-b1f45d00-d477-11ea-9b9e-22f721c41f41.png)

directories path looks suspicious

**Comment by burner1024** [comment]
you want print(a). And maybe print(type(a))

**Comment by egornovivan** [comment]
[debug1.zip](https://github.com/BGforgeNet/msg2po/files/5011424/debug1.zip)

**Comment by burner1024** [comment]
Looks like the issue with natsort version, try 6.x.

**Comment by egornovivan** [comment]
Yep. pip install natsort==6.2.1 fixed the problem
