### ISSUE TITLE
dir2msgstr is removing weidu prompts

### ISSUE THREAD

**Issue by ALIENQuake** [BGforgeNet/msg2po#6]
Commit 1:
https://github.com/InfinityMods/Ascension/commit/6410a56a4a791ac185d66eb5cbf520080e15ac1b#diff-8afcc25bb762c8f5a958b6af0b71f4848588a9b4bb4f77ee63e3cb573ee224e8
Commit 2:
https://github.com/InfinityMods/Ascension/commit/8aafcdca04a2954a38ef3c93388bbc09e473f8f0#diff-8afcc25bb762c8f5a958b6af0b71f4848588a9b4bb4f77ee63e3cb573ee224e8
![image](https://github.com/BGforgeNet/msg2po/assets/365255/9637da55-0bf8-4fa3-b0a9-42f4788f3c5c)

**Comment by burner1024** [comment]
Do you have them in POs?

**Comment by ALIENQuake** [comment]
No, those are new strings only inside french/setup.tra

**Comment by burner1024** [comment]
Then it works as supposed.

**Comment by ALIENQuake** [comment]
So having a non-existent `@tra` reference in the translated language tra files is not supported? What about adding it to English/setup.tra and then pushing updated french tra?

**Comment by burner1024** [comment]
PO files are the translation. TRA files are generated from translation. That's all there is to it.
If you add any strings to source language, they will be available for translation in any other language, like all strings.
However these ones appear to use strange negative indexes, which likely will break something somewhere.

**Comment by ALIENQuake** [comment]
Yes, those are so-called weidu prompts: 

https://github.com/WeiDUorg/weidu/blob/f5d342ecfc990ae0a95faab8753c6f61b599a0e7/examples/prompts.tra

Can you add support for them also?

I've tried to add them inside English tra source:
https://github.com/InfinityMods/WeiDU-Weblate-GitHub/commit/a31a6bdf2d7d957467ea2f167ddc65ddb09f9982

but they are not detected:
https://github.com/InfinityMods/WeiDU-Weblate-GitHub/actions/runs/5058706642/jobs/9079177512#step:3:152

**Comment by burner1024** [comment]
Seems like a niche use case, is it worth it?
I don't think PO format supports negative indexes, but fell free to find evidence to the contrary or suggest something else.

**Comment by burner1024** [comment]
Seems that it's just one language of one mod. Definitely not worth it.
You can just put these into a separate file and load them.

This can be reconsidered when:
1. There's more demand.
2. There's an actual implementation suggested.

**Comment by ALIENQuake** [comment]
Thanks for providing a workaround.

For future reference: https://stackoverflow.com/questions/76316636/does-po-file-format-support-negative-indexes/76350731#76350731

**Comment by burner1024** [comment]
> if you want to use %s in the msgstr, you'll need to convert the PO file to different format, such as gettext format. To convert PO file to the gettext format, you can use the following command

Lol this is a chatgpt answer if I know one.
