### ISSUE TITLE
dir2msgstr removes female context from tra files and it doesn't add it to po files

### ISSUE THREAD

**Issue by ALIENQuake** [BGforgeNet/msg2po#7]
When new tra files for a certain language have a female translation that isn't already present inside the corresponding po file for the given language, dir2msgstr removes female context from tra files and doesn't add it to po files.

Can you add support for this?

**Comment by burner1024** [comment]
Can you show a specific example? A reproducible case.

**Comment by ALIENQuake** [comment]
Using much simpler and cleaner repository:
1. Added female variant: https://github.com/InfinityMods/WeiDU-Weblate-GitHub/commit/abe2cd2224b71a39e919e4e35ec5732dab999f80
2. dir2msgstr doesn't detect it: https://github.com/InfinityMods/WeiDU-Weblate-GitHub/actions/runs/5059499463/jobs/9081122271
3. Even if I run it manually using `@dev`: https://github.com/InfinityMods/WeiDU-Weblate-GitHub/actions/runs/5059522842
4. Next, Hive is overwriting tra: https://github.com/InfinityMods/WeiDU-Weblate-GitHub/commit/23e7472fc1afad0fe9f8aea61037011caabdccf1

**Comment by burner1024** [comment]
Hive does not overwrite anything. It works with PO files, and if it finds a conflict, it refuses to proceed until it's resolved.

This change should fix it, but you better test it on larger content, how adding, removing and changing multiple female lines works.

**Comment by ALIENQuake** [comment]
It seems that it works now, thank you!

1. Added tra with new female strings: https://github.com/InfinityMods/Ascension/commit/5dc3dc3a54a4f013f18f2b146fc635f99197748f
2. Action run: https://github.com/InfinityMods/Ascension/actions/runs/5060231290/jobs/9082824989
3. New female strings are added into french.po: https://github.com/InfinityMods/Ascension/commit/582b432a3d4453d3cc5625a4fcf03b3e3778e336 
4. Weblate seems to have female context:
![image](https://github.com/BGforgeNet/msg2po/assets/365255/263d3d40-57af-4e25-98ea-4768ade445e3)
